### PR TITLE
Update git2 to 0.8

### PR DESCRIPTION
**Pull request by tbehner**

### CODE REVIEW

**Comment by tbehner** [comment]
The travis script is slightly broken. Could you change the installation method of clippy to `rustup component add clippy-preview`? I've resolved all clippy warnings on my pull request.

**Comment by pquentin** [comment]
@tbehner I'm not @xcambar, but why not do it in this pull request?

**Comment by tbehner** [comment]
> @tbehner I'm not @xcambar, but why not do it in this pull request?

Yeah, you are right. I feel silly now...

**Comment by xcambar** [comment]
Thanks for the contribution!

**Pull request merged**
