### PR TITLE
Update old dependencies

### LINKED ISSUE #26: Update outdated dependencies
```bash
% cargo outdated -R
Name       Project  Compat  Latest  Kind    Platform
----       -------  ------  ------  ----    --------
ansi_term  0.9.0    ---     0.11.0  Normal  ---
clap       2.26.1   2.33.0  2.33.0  Normal  ---
dirs       1.0.5    ---     2.0.0   Normal  ---
regex      0.2.2    0.2.11  1.1.6   Normal  ---
try_opt    0.1.1    ---     0.2.0   Normal  ---
```

### PR DESCRIPTION
**Pull request by tesuji**
Based on #30 

Closes #26

### CODE REVIEW

**Comment by xcambar** [comment]
Please update accordingly.

**Comment by tesuji** [comment]
Done.

**Review by xcambar — COMMENTED** [review]
A question, please: Why did the structure of the code (_eg_ `src/precmd.rs`) change?

**Comment by tesuji** [comment]
I think it is mostly whitespaces changes. You could hide whitespaces changes
and review it again.
image

**Review by xcambar — APPROVED** [review]

**Comment by xcambar** [comment]
Indeed. The diff view was messy, with this one.
Thanks for the contribution.

**Comment by tesuji** [comment]
You're welcome.

**Pull request merged**
