### PR TITLE
turns git status into an Option<String> #7

### PR DESCRIPTION
**Pull request by jbolila**
maybe you want to sign somehow the initial state, this is i guess the simplest fix.

### CODE REVIEW

**Comment by xcambar** [comment]
Ok, I've learnt 3 things with this PR:

* prefer match over unwrap
* `Option` are awesome
* `unwrap_or_default`

Did I read that correctly?

**Comment by xcambar** [comment]
Thanks a lot!

**Comment by nkoehring** [comment]
The code could be shortened a lot by using the `?` operator and returning a Result instead.

```rust
fn repo_status(r: &Repository) -> Result<String, String> {
    let mut opts = StatusOptions::new();
    opts.include_untracked(true);

    let shorthand = Cyan.paint(r.head()?.shorthand().unwrap_or_default().into());
    let statuses = r.statuses(Some(&mut opts))?;
   
    // … some lines omitted

    Ok(ANSIStrings(&out).to_string())
}
```

The rest works the same then.


**Disclaimer**: I just wrote that code in the comment field. It is not tested at all, so the compiler might complain :angel: 

Read more here: https://m4rw3r.github.io/rust-questionmark-operator

**Comment by jbolila** [comment]
It's true, an Option just shows this as a self contained (and non critical) error. In the other end I was looking for a way to unwrap_or return None, but I'm not aware of any way of doing that, let me know if you know of any.

Has a general comment, I think is not much usual have prompts giving detailed errors in the terminal.

**Comment by nkoehring** [comment]
@jbolila Of course the error should be, if at all, logged via a logger at least to stdout. The purpose of a Result type is not only error reporting but handling things that can fail out of various reasons. Getting the repository status is error prone, so the Result type is semantically correct. In most cases the error can be ignored and no git status shown.

**Comment by jbolila** [comment]
@nkoehring that's a good point to consider in general to remove `unwrap` handle the error properly and find a single way to communicate the error messages to the user, and to make life easier maybe use [error-chain](https://github.com/rust-lang-nursery/error-chain), like in the [rust cookbook](https://rust-lang-nursery.github.io/rust-cookbook/intro.html) and many other projects..

**Pull request merged**
